openapi: 3.0.0
info:
    title: 'BrightCarbon API'
    version: '1.0.0'
    description: "API documentation for BrightCarbon's notes API"
servers:
  - url: http://localhost:5000

tags:
  - name: Authentication
    description: Authentication-related routes
  - name: Notes
    description: Routes related to notes management
  - name: VersionHistory
    description: Routes for managing note version history

paths:
  /register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      description: Register a new user with a username, email, and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The user's chosen username
                  example: johndoe
                email:
                  type: string
                  description: The user's email address
                  example: johndoe@example.com
                password:
                  type: string
                  description: The user's password
                  example: Password123
      responses:
        '201':
          description: User successfully registered
        '400':
          description: Bad request, invalid input
        '500':
          description: Internal server error

  /login:
    post:
      tags:
        - Authentication
      summary: Log in a user
      description: Authenticate a user and return a JWT token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The user's email
                  example: johndoe@example.com
                password:
                  type: string
                  description: The user's password
                  example: Password123
      responses:
        '200':
          description: Login successful, returning JWT token
        '401':
          description: Unauthorized, invalid credentials
        '500':
          description: Internal server error

  /notes:
    get:
      tags:
        - Notes
      summary: Retrieve all notes
      description: Get a list of all notes for the authenticated user.
      responses:
        '200':
          description: Successfully retrieved notes
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

    post:
      tags:
        - Notes
      summary: Create a new note
      description: Create a new note with title, content, and tags.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: The title of the note
                content:
                  type: string
                  description: The content of the note
                tags:
                  type: array
                  description: Tags associated with the note
                  items:
                    type: string
      responses:
        '201':
          description: Note created successfully
        '400':
          description: Bad request, invalid input
        '500':
          description: Internal server error

  /notes/{id}:
    get:
      tags:
        - Notes
      summary: Get a note by ID
      description: Retrieve a note by its ID for the authenticated user.
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the note
      responses:
        '200':
          description: Note retrieved successfully
        '404':
          description: Note not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

    put:
      tags:
        - Notes
      summary: Update a note by ID
      description: Update a note's title, content, and tags by its ID.
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the note
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Note updated successfully
        '404':
          description: Note not found
        '400':
          description: Bad request, invalid input
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

    delete:
      tags:
        - Notes
      summary: Delete a note by ID
      description: Delete a note by its ID.
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the note
      responses:
        '200':
          description: Note deleted successfully
        '404':
          description: Note not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /notes/{id}/archive:
    put:
      tags:
        - Notes
      summary: Archive a note
      description: Archive a note by setting its `isArchived` field to true.
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the note
      responses:
        '200':
          description: Note archived successfully
        '404':
          description: Note not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /versions/{noteId}:
    get:
      tags:
        - VersionHistory
      summary: Get all versions for a note
      description: Retrieve all versions for a specific note.
      parameters:
        - in: path
          name: noteId
          schema:
            type: string
          required: true
          description: The ID of the note
      responses:
        '200':
          description: Successfully retrieved versions
        '404':
          description: Versions not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

    delete:
      tags:
        - VersionHistory
      summary: Delete all versions for a note
      description: Delete all versions for a specific note.
      parameters:
        - in: path
          name: noteId
          schema:
            type: string
          required: true
          description: The ID of the note
      responses:
        '200':
          description: Versions deleted successfully
        '404':
          description: Versions not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /versions/{noteId}/{versionId}/restore:
    put:
      tags:
        - VersionHistory
      summary: Restore a note to a specific version
      description: Restore a note to the state of a specific version.
      parameters:
        - in: path
          name: noteId
          schema:
            type: string
          required: true
          description: The ID of the note
        - in: path
          name: versionId
          schema:
            type: string
          required: true
          description: The ID of the version
      responses:
        '200':
          description: Note restored successfully
        '404':
          description: Version not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

